### ISSUE TITLE
Conflict with PyStan

### ISSUE THREAD

**Issue by Knifa** [GoogleCloudPlatform/google-auth-library-python#222]
#### Description:
There's some sort of conflict between PyStan and the Google Auth libs due to the use of pyximport.

For more context, we recently introduced Facebook's Prophet (which uses PyStan) into our project which already used Pandas + Panda's BigQuery libs (which use Google's BigQuery libs, which includes this auth libs). We discovered importing Prophet causes anything involving BigQuery to explode with a horrific traceback.

You can find the original issue I raised on Prophet at facebook/prophet#363.
I've raised an issue with PyStan as well at stan-dev/pystan#399.

#### Reproducible Steps:
General breaking case found by @bletham on facebook/prophet#363 (probably most relevant):

```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
from google.auth import app_engine
```

Our working test (prompts for authentication):
```
import pandas as pd

df = pd.read_gbq('test', 'test')
```

Our breaking test:
```
import pandas as pd
from fbprophet import Prophet

df = pd.read_gbq('test', 'test')
```

Gives this traceback:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 879, in _find_spec
AttributeError: 'PyxImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    df = pd.read_gbq('give me an error', 'a project id')
  File "./venv/lib/python3.6/site-packages/pandas/io/gbq.py", line 100, in read_gbq
    **kwargs)
  File "./venv/lib/python3.6/site-packages/pandas_gbq/gbq.py", line 906, in read_gbq
    dialect=dialect, auth_local_webserver=auth_local_webserver)
  File "./venv/lib/python3.6/site-packages/pandas_gbq/gbq.py", line 202, in __init__
    self.credentials = self.get_credentials()
  File "./venv/lib/python3.6/site-packages/pandas_gbq/gbq.py", line 214, in get_credentials
    credentials = self.get_application_default_credentials()
  File "./venv/lib/python3.6/site-packages/pandas_gbq/gbq.py", line 243, in get_application_default_credentials
    credentials, _ = google.auth.default(scopes=[self.scope])
  File "./venv/lib/python3.6/site-packages/google/auth/_default.py", line 287, in default
    credentials, project_id = checker()
  File "./venv/lib/python3.6/site-packages/google/auth/_default.py", line 164, in _get_gae_credentials
    from google.auth import app_engine
  File "./venv/lib/python3.6/site-packages/google/auth/app_engine.py", line 32, in <module>
    from google.appengine.api import app_identity
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 946, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 881, in _find_spec
  File "<frozen importlib._bootstrap>", line 855, in _find_spec_legacy
  File "./venv/lib/python3.6/site-packages/pyximport/pyximport.py", line 253, in find_module
    fp, pathname, (ext,mode,ty) = imp.find_module(fullname,package_path)
  File "~/.pyenv/versions/3.6.1/lib/python3.6/imp.py", line 270, in find_module
    "not {}".format(type(path)))
RuntimeError: 'path' must be None or a list, not <class '_frozen_i
```

Requirements with this setup:
```
cachetools==2.0.1
certifi==2017.11.5
chardet==3.0.4
cycler==0.10.0
Cython==0.27.3
fbprophet==0.2.1
google-api-python-client==1.6.4
google-auth==1.2.1
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.2.0
httplib2==0.10.3
idna==2.6
matplotlib==2.1.0
numpy==1.13.3
oauth2client==4.1.2
oauthlib==2.0.6
pandas==0.21.0
pandas-gbq==0.2.0
pyasn1==0.3.7
pyasn1-modules==0.1.5
pyparsing==2.2.0
pystan==2.17.0.0
python-dateutil==2.6.1
pytz==2017.3
requests==2.18.4
requests-oauthlib==0.8.0
rsa==3.4.2
six==1.11.0
uritemplate==3.0.0
urllib3==1.22
```

#### Versions
pystan 2.17.0.0
google-auth 1.2.1
Python 3.6.1
macOS 10.1.2.3

**Comment by jonparrott** [comment]
We don't use pyximport or cython anywhere in this library or in the
bigquery library. They're both pure Python.

**Comment by Knifa** [comment]
Sorry, my mistake. PyStan is the one using pyximport. looking more like the cause is there (or due to pyximport itself).

**Comment by jonparrott** [comment]
No worries, let us know if we can do anything to help, but I'm going to close this for now.
