### ISSUE TITLE
pyasn1 import error in Google Compute Engine

### ISSUE THREAD

**Issue by hiranya911** [GoogleCloudPlatform/google-auth-library-python#229]
Saw the following error when trying to import `firebase_admin` in a GCE instance:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/firebase_admin/__init__.py", line 22, in <module>
    from firebase_admin import credentials
  File "/usr/local/lib/python2.7/dist-packages/firebase_admin/credentials.py", line 23, in <module>
    from google.oauth2 import service_account
  File "/usr/local/lib/python2.7/dist-packages/google/oauth2/service_account.py", line 77, in <module>
    from google.auth import _service_account_info
  File "/usr/local/lib/python2.7/dist-packages/google/auth/_service_account_info.py", line 22, in <module>
    from google.auth import crypt
  File "/usr/local/lib/python2.7/dist-packages/google/auth/crypt/__init__.py", line 39, in <module>
    from google.auth.crypt import rsa
  File "/usr/local/lib/python2.7/dist-packages/google/auth/crypt/rsa.py", line 17, in <module>
    from google.auth.crypt import _python_rsa
  File "/usr/local/lib/python2.7/dist-packages/google/auth/crypt/_python_rsa.py", line 29, in <module>
    from pyasn1_modules.rfc2459 import Certificate
  File "/usr/local/lib/python2.7/dist-packages/pyasn1_modules/rfc2459.py", line 20, in <module>
    from pyasn1.type import opentype
ImportError: cannot import name opentype
```

I later installed `google-auth-oauthlib` on the same instance, which pulled in some missing `pyasn` modules after which the problem went away. Should `google-auth` update its dependency declarations so this won't happen again?

**Comment by jonparrott** [comment]
pyasn1 is a [direct dependency](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/setup.py#L22) of this library. Can you let me know some exact steps to reproduce this? Which GCE image did you use? Did you install in a virtualenv or not?

**Comment by hiranya911** [comment]
@jonparrott virtualenv was not in use. I just installed [`firebase-admin`](https://pypi.python.org/pypi/firebase-admin), which declares `google-auth` as a direct dependency:

```sudo pip install firebase-admin```

And then a simple import was enough to reproduce the error:

```python -c 'import firebase_admin'```

I started my GCE instance as follows (an image was not specified explicitly):

```
gcloud compute instances create flask-demo
gcloud compute instances start flask-demo
```

**Comment by jonparrott** [comment]
On debian stretch I tried reproducing this by doing the following:

```
$ sudo apt install python python-pip
...
$ sudo pip install firebase-admin
jonwayne@test-auth-bug:~$ sudo pip install firebase-admin
Collecting firebase-admin
  Downloading firebase_admin-2.6.0-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 1.1MB/s
Collecting requests>=2.13.0 (from firebase-admin)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 4.2MB/s
Collecting google-cloud-storage>=1.2.0 (from firebase-admin)
  Downloading google_cloud_storage-1.6.0-py2.py3-none-any.whl (51kB)
    100% |████████████████████████████████| 61kB 6.6MB/s
Requirement already satisfied: enum34>=1.0.4; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from firebase-admin)
Collecting google-auth>=1.1.0 (from firebase-admin)
  Downloading google_auth-1.2.1-py2.py3-none-any.whl (61kB)
    100% |████████████████████████████████| 61kB 6.1MB/s
Requirement already satisfied: six>=1.6.1 in /usr/lib/python2.7/dist-packages (from firebase-admin)
Collecting google-cloud-firestore>=0.27.0 (from firebase-admin)
  Downloading google_cloud_firestore-0.28.0-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 4.5MB/s
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.13.0->firebase-admin)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 4.6MB/s
Collecting idna<2.7,>=2.5 (from requests>=2.13.0->firebase-admin)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 7.6MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.13.0->firebase-admin)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 4.9MB/s
Collecting certifi>=2017.4.17 (from requests>=2.13.0->firebase-admin)
  Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
    100% |████████████████████████████████| 337kB 3.1MB/s
Collecting google-api-core<0.2.0dev,>=0.1.1 (from google-cloud-storage>=1.2.0->firebase-admin)
  Downloading google_api_core-0.1.2-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 7.3MB/s
Collecting google-cloud-core<0.29dev,>=0.28.0 (from google-cloud-storage>=1.2.0->firebase-admin)
  Downloading google_cloud_core-0.28.0-py2.py3-none-any.whl
Collecting google-resumable-media>=0.3.1 (from google-cloud-storage>=1.2.0->firebase-admin)
  Downloading google_resumable_media-0.3.1-py2.py3-none-any.whl
Collecting cachetools>=2.0.0 (from google-auth>=1.1.0->firebase-admin)
  Downloading cachetools-2.0.1-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from google-auth>=1.1.0->firebase-admin)
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 6.8MB/s
Collecting pyasn1-modules>=0.0.5 (from google-auth>=1.1.0->firebase-admin)
  Downloading pyasn1_modules-0.2.1-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 5.1MB/s
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python2.7/dist-packages (from google-auth>=1.1.0->firebase-admin)
Collecting google-gax<0.16dev,>=0.15.7 (from google-cloud-firestore>=0.27.0->firebase-admin)
  Downloading google_gax-0.15.16-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 7.9MB/s
Collecting googleapis-common-protos<2.0dev,>=1.5.3 (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-storage>=1.2.0->firebase-admin)
  Downloading googleapis-common-protos-1.5.3.tar.gz
Collecting futures>=3.2.0; python_version < "3.2" (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-storage>=1.2.0->firebase-admin)
  Downloading futures-3.2.0-py2-none-any.whl
Collecting protobuf>=3.0.0 (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-storage>=1.2.0->firebase-admin)
  Downloading protobuf-3.5.0.post1-cp27-cp27mu-manylinux1_x86_64.whl (6.4MB)
    100% |████████████████████████████████| 6.4MB 199kB/s
Collecting setuptools>=34.0.0 (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-storage>=1.2.0->firebase-admin)
  Downloading setuptools-38.2.4-py2.py3-none-any.whl (489kB)
    100% |████████████████████████████████| 491kB 2.6MB/s
Collecting pytz (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-storage>=1.2.0->firebase-admin)
  Downloading pytz-2017.3-py2.py3-none-any.whl (511kB)
    100% |████████████████████████████████| 512kB 2.8MB/s
Collecting future<0.17dev,>=0.16.0 (from google-gax<0.16dev,>=0.15.7->google-cloud-firestore>=0.27.0->firebase-admin)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 1.2MB/s
Collecting dill<0.3dev,>=0.2.5 (from google-gax<0.16dev,>=0.15.7->google-cloud-firestore>=0.27.0->firebase-admin)
  Downloading dill-0.2.7.1.tar.gz (64kB)
    100% |████████████████████████████████| 71kB 10.5MB/s
Collecting ply==3.8 (from google-gax<0.16dev,>=0.15.7->google-cloud-firestore>=0.27.0->firebase-admin)
  Downloading ply-3.8.tar.gz (157kB)
    100% |████████████████████████████████| 163kB 3.9MB/s
Collecting grpcio<2.0dev,>=1.0.2 (from google-gax<0.16dev,>=0.15.7->google-cloud-firestore>=0.27.0->firebase-admin)
  Downloading grpcio-1.8.1-cp27-cp27mu-manylinux1_x86_64.whl (6.0MB)
    100% |████████████████████████████████| 6.0MB 146kB/s
Building wheels for collected packages: googleapis-common-protos, future, dill, ply
  Running setup.py bdist_wheel for googleapis-common-protos ... done
  Stored in directory: /root/.cache/pip/wheels/93/e0/cb/b06866f012310b96fba79c37f199aaf973a2e97a42ca7ef696
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /root/.cache/pip/wheels/c2/50/7c/0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
  Running setup.py bdist_wheel for dill ... done
  Stored in directory: /root/.cache/pip/wheels/e5/88/fe/7e290ce5bb39d531eb9bee5cf254ba1c3e3c7ba3339ce67bee
  Running setup.py bdist_wheel for ply ... done
  Stored in directory: /root/.cache/pip/wheels/6f/23/3c/7055bf8004cee3c7d06c46318014e0374539094c4e36246e9a
Successfully built googleapis-common-protos future dill ply
Installing collected packages: urllib3, idna, chardet, certifi, requests, setuptools, protobuf, googleapis-common-protos, cachetools, rsa, pyasn1-modules, google-auth, futures, pytz, google-api-core, google-cloud-core, google-resumable-media, google-cloud-storage, future, dill, ply, grpcio, google-gax, google-cloud-firestore, firebase-admin
  Found existing installation: urllib3 1.19.1
    Not uninstalling urllib3 at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: idna 2.2
    Not uninstalling idna at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: chardet 2.3.0
    Not uninstalling chardet at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: requests 2.12.4
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: setuptools 33.1.1
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed cachetools-2.0.1 certifi-2017.11.5 chardet-3.0.4 dill-0.2.7.1 firebase-admin-2.6.0 future-0.16.0 futures-3.2.0 google-api-core-0.1.2 google-auth-1.2.1 google-cloud-core-0.28.0 google-cloud-firestore-0.28.0 google-cloud-storage-1.6.0 google-gax-0.15.16 google-resumable-media-0.3.1 googleapis-common-protos-1.5.3 grpcio-1.8.1 idna-2.6 ply-3.8 protobuf-3.5.0.post1 pyasn1-modules-0.2.1 pytz-2017.3 requests-2.18.4 rsa-3.4.2 setuptools-38.2.4 urllib3-1.22
```

The line that's causing us heartburn is this one:

```
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python2.7/dist-packages (from google-auth>=1.1.0->firebase-admin)
```

It seem debian already has pyasn1:

```
pip show pyasn1
Name: pyasn1
Version: 0.1.9
Summary: ASN.1 types and codecs
Home-page: http://sourceforge.net/projects/pyasn1/
Author: Ilya Etingof <ilya@glas.net>
Author-email: ilya@glas.net
License: BSD
Location: /usr/lib/python2.7/dist-packages
Requires:
```

Buy `pyasn1_modules` expects a later version. It seems the minimum version is [0.4.1](https://github.com/etingof/pyasn1/releases/tag/v0.4.1). So we just need to update setup.py to reflect that. PR incoming.

**Comment by gBokiau** [comment]
Is a new release that would fix this due soon ?

**Comment by jonparrott** [comment]
@gBokiau It'll be in v1.3.0, release PR is #233

**Comment by gBokiau** [comment]
Yay! Works! 🎉

**Comment by raduolivas** [comment]
I fixed everything using virtualenv.
