### ISSUE TITLE
google.auth.exceptions.RefreshError: Internal Failure. Random exception with a few concurrent authentications with service account in json file

### ISSUE THREAD

**Issue by kosmiciatakuja** [GoogleCloudPlatform/google-auth-library-python#246]
I'm running a couple of concurrent Google Speech requests and quite frequently an exception occurs with the following traceback:

```
ERROR:root:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f5ce8fd20f0>" raised exception!
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/grpc/_plugin_wrapping.py", line 77, in __call__
    callback_state, callback))
  File "/usr/lib/python3.6/site-packages/google/auth/transport/grpc.py", line 77, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/usr/lib/python3.6/site-packages/google/auth/transport/grpc.py", line 65, in _get_authorization_headers
    headers)
  File "/usr/lib/python3.6/site-packages/google/auth/credentials.py", line 121, in before_request
    self.refresh(request)
  File "/usr/lib/python3.6/site-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/usr/lib/python3.6/site-packages/google/oauth2/_client.py", line 145, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/usr/lib/python3.6/site-packages/google/oauth2/_client.py", line 111, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/usr/lib/python3.6/site-packages/google/oauth2/_client.py", line 61, in _handle_error_response
    error_details, response_body)
google.auth.exceptions.RefreshError: ('internal_failure: None', '{\n  "error" : "internal_failure"\n}')
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 54, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/grpc/_channel.py", line 341, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Getting metadata from plugin failed with error: ('internal_failure: None', '{\n  "error" : "internal_failure"\n}'))>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/asterisk/agi-bin/agi_devel/gasr.py", line 112, in <module>
    for response in responses:
  File "/usr/lib/python3.6/site-packages/grpc/_channel.py", line 347, in __next__
    return self._next()
  File "/usr/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 56, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: ('internal_failure: None', '{\n  "error" : "internal_failure"\n}')
```

Authentication is handled with a service account and a json file. Here's the relevant code bit, it's not much:

```
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/home/arch/agi/google_service_account.json"
from google.cloud import speech
speech = speech.SpeechClient()
```

The issue is somewhat random, but only appears when there are a couple of concurrent recognition requests. It never got it when running one request at a time.

**Comment by jonparrott** [comment]
Hrm. We don't go out of our way to ensure thread safety but the *worst* case scenario is that the credentials get refreshed multiple times within a second.

If you manually refresh these credentials before running your script, what do you see?

```python
import google.auth
import google.auth.transport.requests

credentials, _ = google.auth.default(scopes=['https://www.googleapis.com/auth/cloud-platform'])
credentials.refresh(google.auth.transport.requests.Request())

from google.cloud import speech
speech = speech.SpeechClient(credentials=credentials)

...
```

**Comment by theacodes** [comment]
I'm closing this due to inactivity. If you can reproduce this with the latest grpcio, let us know and we'll re-open.

**Comment by umair-tp** [comment]
I am in the same situation, what do you suggest ?

```
Traceback (most recent call last):
  File "aadhaar_template_test_suite.py", line 17, in <module>
    id = IdFactory(image)
  File "/Users/mohammadumair/workspace/dolphin-env/dolphin/ekyc/core/base.py", line 144, in IdFactory
    return detect_id(image_content)
  File "/Users/mohammadumair/workspace/dolphin-env/dolphin/ekyc/core/base.py", line 65, in detect_id
    detected_words = detect_words(image)
  File "/Users/mohammadumair/workspace/dolphin-env/dolphin/ekyc/core/utils.py", line 295, in detect_words
    detected_text = str(detect_document_text(image).full_text_annotation.text)
  File "/Users/mohammadumair/workspace/dolphin-env/dolphin/ekyc/core/utils.py", line 281, in detect_document_text
    client = vision.ImageAnnotatorClient(credentials=get_refreshed_credentials())
  File "/Users/mohammadumair/workspace/dolphin-env/dolphin/ekyc/core/utils.py", line 275, in get_refreshed_credentials
    credentials.refresh(google.auth.transport.requests.Request())
  File "/Users/mohammadumair/workspace/dolphin-env/lib/python3.6/site-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/Users/mohammadumair/workspace/dolphin-env/lib/python3.6/site-packages/google/oauth2/_client.py", line 145, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/Users/mohammadumair/workspace/dolphin-env/lib/python3.6/site-packages/google/oauth2/_client.py", line 106, in _token_endpoint_request
    method='POST', url=token_uri, headers=headers, body=body)
  File "/Users/mohammadumair/workspace/dolphin-env/lib/python3.6/site-packages/google/auth/transport/requests.py", line 124, in __call__
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1102a9be0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

```

**Comment by sushilverma208016** [comment]
Thanks theacodes,
The manually refresh thing worked for me.
